name=WiFi_Manager
version=1.0.0
author=Ade Firman
maintainer=Ade Firman <adilllfirman@gmail.com>
sentence=Library wrapper untuk WiFiManager dan Preferences dengan konfigurasi MQTT bawaan.
paragraph=Library ini membungkus tzapu/WiFiManager dan Preferences ESP32 untuk memudahkan penyambungan WiFi secara otomatis sekaligus mengonfigurasi parameter MQTT (Server, Port, Username, Password, Client ID, dan Topic) melalui Captive Portal.
category=Communication
url=https://github.com/0ADILL3/WiFi_Manager
architectures=esp32
depends=WiFiManager,Preferences
includes=WiFi_Manager.h