name=WiFi_Manager
version=2.1.0
author=Ade Firman
maintainer=Ade Firman <adilllfirman@gmail.com>
sentence=Library wrapper tangguh untuk WiFiManager dan Preferences ESP32 dengan fitur parameter dinamis dan mode non-blocking.
paragraph=Library ini membungkus tzapu/WiFiManager dan Preferences ESP32 untuk menyederhanakan penyambungan WiFi. Dilengkapi dengan penyimpanan parameter kustom dinamis ke NVS, auto-reconnect, dan dukungan Captive Portal asinkron (non-blocking).
category=Communication
url=https://github.com/0ADILL3/WiFi_Manager
architectures=esp32
depends=WiFiManager,Preferences
includes=WiFi_Manager.h